- internal/provider/generate.go
When creating the cache directory to place the provider, the
architecture and OS is hardcoded to `linux_amd64`. This means that when
running the tool on MacOS it fails like this:
```
Error while installing hashicorp/myprovider v0.0.1: provider
registry.terraform.io/hashicorp/myprovider 0.0.1 is not available for darwin_amd64
```
This change generates the path based on the OS and arch.
> Detect os and arch

- internal/provider/generate.go
Small scoping bug was preventing the tool from importing the import
shell script
> Fix import functionality

- schemamd/render.go
Terraform SDK will inject an `id` field to the provider schema without
setting its description. This PR adds a default description.
> Add default description for the `id` field.

- schemamd/render_test.go
Normalize our expected output to strip out the `\r` characters git
inserts when checking out files on Windows so our Windows tests aren't
flaky anymore.
> Fix newline differences in tests.

- go.mod
- go.sum
- internal/cmd/generate.go
- internal/provider/generate.go
Signed-off-by: Gennady Lipenkov <xgen@yandex-team.ru>
> Support 'offline mode': do not download terraform binary

- CHANGELOG.md
- README.md
- internal/provider/template.go
This is an excellent piece of tooling that we are finding very helpful
as we develop a new HPE GreenLake provider (called hpegl) that we will
publish to the Provider Registry.  We're using this tool to generate
documentation.  We'd like the ability to set the "subcategory" field in
the resource and data-source templates.  Our provider will support a
number of different services and the naming will be the following:
hpegl_< service mnemonic >_< service resource or data-source >
We want to extract the service mnemonic from the name and add that as a
"subcategory".  I've added a "split" template function which is set to
strings.Split.  With this template function I can add the following to a
template:
subcategory: {{ $arr := split .Name "_" }}"{{ index $arr 1  }}"
To extract the service …
> Add "split" template function for use with strings

- CHANGELOG.md
- internal/provider/generate.go
- internal/provider/template.go
- internal/provider/util.go
- internal/provider/util_test.go
Currently, it is not possible to have single word `resources` or `data sources` (e.g., `http`) use templates in the generation of docs. This PR addresses that by allowing single word resources and data sources to use a matching template (e.g., `http` data source using `http.md.tmpl` template).
An error is now returned if a resource cannot be found using either the provider short name or the provider short name concatenated with the template file name.
> Allowing single word resources to use templates

- CHANGELOG.md
- internal/provider/generate.go
After updating to 0.9.0, I found that individual template overrides no
longer worked using the `generate` command however, would work if using
`tfplugindocs` directly. I started looking into why this was and it
boiled down to being that the value from `--rendered-provider-name` was
being incorrectly passed into `resourceSchema` causing the friendly name
(such as `Cloudflare`) to be used instead of the correct schema name
(here, `terraform-provider-cloudflare`) resulting in the schema never
being found for the data-source or resource. This corrects the value we
pass to the render website methods to always be the schema provider, not
the friendly name.
Closes #139
> generate: pass through correct name of schema provider

- CHANGELOG.md
- internal/provider/generate.go
- internal/provider/template.go
Updates the templating variables to include `RenderedProviderName` which is the
value from `--rendered-provider-name` when invoking `generate`.
Allows doing the following in templates resulting in a nicer docs experience.
```
page_title: "{{.Name}} {{.Type}} - {{.RenderedProviderName}}"
```
Output:
```
page_title: "Example Resource - terraform-provider-cloudflare"
page_title: "Example Resource - Cloudflare"
```
> expose `RenderedProviderName` to templating

- CHANGELOG.md
- internal/provider/generate.go
- internal/provider/util.go
- internal/provider/util_test.go
The changes present in `v0.10.0` result in an error being generated if `providerShortName` or `providerShortName` concatenated with the template filename (following stripping of file extensions) are not found in the _data source_ or _resource_ schemas.
This PR reinstates the behaviour present in `v0.9.0`, where the failure to find the schema does not result in an error.
> Do not error if data source or resource not found in schemas

- CHANGELOG.md
- README.md
- internal/provider/generate.go
When building custom templates, we have [`HasExample`](https://github.com/hashicorp/terraform-plugin-docs/blob/6e1a3339859e55625941bcef8ab365552235ca3b/internal/provider/template.go#L137) and
[`HasImport`](https://github.com/hashicorp/terraform-plugin-docs/blob/6e1a3339859e55625941bcef8ab365552235ca3b/internal/provider/template.go#L140) available that return a boolean value and allow templates
to include conditionals. Some uses of this would be to only show either
an example or import line should the files exist. However, when we are
calling these for templates both data-sources and resources [only pass in an
empty string](https://github.com/hashicorp/terraform-plugin-docs/blob/6e1a3339859e55625941bcef8ab365552235ca3b/internal/provider/generate.go#L420) resulting in the value always …
> cmd/generate: allow `HasExample` and `HasImport` to function

- schemamd/render.go
The `path` slice needs to be made a copy of the `parents`, otherwise when there is enough nesting, the `append` operation does not do a copy of the slice, and we keep modifying the same reference in the nested blocks, thus generating incorrect titles and links.
As an example, you can check https://registry.terraform.io/providers/DataDog/datadog/2.25.0/docs/resources/dashboard#nestedblock--widget--change_definition--request--apm_query, which is the level of nesting things start to go bad. The title shows the wrong `path`, but the anchor ID is still ok at this point.
Related issue: https://github.com/DataDog/terraform-provider-datadog/issues/1024
> Fix title and reference links of nested blocks/attributes

- CHANGELOG.md
- README.md
- go.mod
- go.sum
* Refreshing dependencies
* Updated CHANGELOG
* Updated README to explicitly report the output of the `--help` command ("Usage" section), as a quick and dirty way to document the flags supported by the commands
> Prepare for `v0.11.0` release

- CHANGELOG.md
- README.md
- internal/provider/template.go
This is a regression from https://github.com/hashicorp/terraform-plugin-docs/pull/155: unfortunately the logic didn't check that the file where an example/import was expected, actually existed.
Additionally, given I had to spend time figuring out a bit more how those data fields are populated, I caught the opportunity to finally document the data fields.
As a bonus, I added 3 template functions that were very low hanging fruits: `lower`, `upper` and `title`.
> Fix regression with `HasImport`/`HasExample` data fields, and (finally) document template data fields

- .github/workflows/test.yml
- .golangci.yml
- internal/cmd/generate.go
- internal/cmd/validate.go
- internal/mdplain/renderer.go
- internal/provider/generate.go
- internal/provider/template_test.go
- internal/provider/util.go
- internal/provider/util_test.go
- internal/tmplfuncs/tmplfuncs.go
- schemamd/behaviors_test.go
- schemamd/render.go
- schemamd/render_test.go
- schemamd/write_attribute_description_test.go
- schemamd/write_block_type_description_test.go
- schemamd/write_nested_attribute_type_description_test.go
- schemamd/write_type_test.go
contributes to:
- https://github.com/hashicorp/terraform-providers-devex-internal/issues/102
- https://github.com/hashicorp/terraform-providers-devex-internal/issues/83
- https://github.com/hashicorp/terraform-providers-devex-internal/issues/126
- Fixed deprecation of `ioutil` in favor of `os` std package
> ci: add `golangci` linting + fixed deprecations

- .changes/unreleased/BUG FIXES-20230301-091541.yaml
- go.mod
- go.sum
Closes #228 
A recent update of `tfexec` [v0.18.0](https://github.com/hashicorp/terraform-exec/releases/tag/v0.18.0) caused a regression where detailed stderr information wasn't being passed to downstream modules. This has now been fixed with the new release [v0.18.1](https://github.com/hashicorp/terraform-exec/releases/tag/v0.18.1)
While the docs tool doesn't use this error information directly, this caused a situation where upgrading `terraform-plugin-docs` from `0.13.0` to `0.14.0` could cause acceptance tests to fail if the consuming module also uses `terraform-plugin-testing` or `terraform-plugin-sdk`.
**Examples:**
- https://github.com/hashicorp/terraform-provider-tls/pull/327
- https://github.com/hashicorp/terraform-provider-tls/actions/runs/4296411115
> Bump `terraform-exec` to `v0.18.1`

- .changes/unreleased/BREAKING CHANGES-20230606-092955.yaml
- README.md
- internal/cmd/generate.go
- internal/provider/generate.go
The "legacy sidebar" file was an `.erb` file that was used to render the side navigation when provider documentation was centrally gathered and hosted on the terraform.io website. Since the introduction of the public Terraform Registry, the side navigation is determined via the `subcategory` property in YAML frontmatter of documentation pages. The flag, which never actually implemented any logic and instead logged a "TODO" warning, is extremely unlikely to be used anywhere in practice.
> generate: Remove legacy-sidebar flag

- .golangci.yml
Reference: https://github.com/hashicorp/terraform-plugin-docs/actions/runs/5191760369/jobs/9360009612
Reference: https://github.com/hashicorp/terraform-plugin-framework/blob/1e82228e6631748852c4cd00b6c7e1c0c1a4cfc2/.golangci.yml#L27-L29
Similar to other terraform-plugin-* repositories.
> ci: Set golangci-lint run timeout to 5 minutes

- README.md
- internal/cmd/generate.go
Closes #323 
Not sure if we also want to make an official recommendation on using the latest version of Terraform for generating the docs?
> Document the default behavior of `--tf-version` and usage of Terraform binary

- .changes/unreleased/BUG FIXES-20240124-131519.yaml
- cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_docs_website.txtar
- cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_legacy_website.txtar
- internal/provider/migrate.go
- internal/provider/util.go
Closes: #326 
Changes the code templates references to use relative paths (relative to provider directory) from absolute paths.
> Output relative paths for `migrate` code template references

- go.mod
- go.sum
- internal/mdplain/mdplain.go
- internal/mdplain/mdplain_test.go
- internal/mdplain/renderer.go
- internal/mdplain/testdata/markdown.md
- internal/mdplain/testdata/mdplain.txt
Closes: #321 
This PR adds a golden file test for the `PlainMarkdown()` function and refactors the `mdplain` package to use `yuin/goldmark` library instead of `russross/blackfriday` for markdown processing.
> Refactor `mdplain` package to use `yuin/goldmark` library for markdown processing

- .changes/unreleased/BUG FIXES-20240327-161037.yaml
- .changes/unreleased/ENHANCEMENTS-20240327-160831.yaml
- README.md
- cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_docs_website_with_prefix.txtar
- cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_legacy_website_with_prefix.txtar
- internal/cmd/migrate.go
- internal/provider/migrate.go
Closes: #347 
Supersedes: #348 
Fixes a bug that is encountered when the `migrate` command and `generate` command are run on provider documentation that have provider short name prefixes in their filenames (ex. `time_rotating.md`). The `migrate` command would move the files to the template folder as-is but the `generate` command does not recognize these files as valid documentation files because of the prefix, and therefore generates default template for the "missing" resource/data-sources, resulting in duplicate templates. This PR resolves this by introducing a `--provider-name` flag to the `migrate` subcommand, and uses the provided value to derive the provider short name and strips the prefix from an file name containing it. 
The `--provider-name` flag is optional for users who do not …
> Strip Provider Prefix from File Names during Migration

- .changes/0.19.0.md
- CHANGELOG.md
Closes: #355 
PR #332 refactored the `mdplain` package and reimplemented the `plainmarkdown` function using the `yuin/goldmark` library. The purpose of the `plainmarkdown` function is to strip out markdown elements to render the input as plain text, primarily for the YAML frontmatter. The previous implementation of `plainmarkdown` still kept some markdown formatting elements such as links and bulletpoints but removed others like headers. The new implementation in PR #332 now strips out all markdown formatting elements but a changelog entry associated with this change was not included in the `v0.19.0` release. 
This PR retroactively adds a changelog entry into the Changie `0.19.0.md` changelog file and `CHANGELOG.md`
> Add `plainmarkdown` breaking change entry to `v0.19.0` changelog

- .changes/unreleased/BUG FIXES-20240426-095042.yaml
- cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_idempotency.txtar
- internal/provider/migrate.go
Closes #362
To reproduce, copied an existing test case and ensured the test script included multiple `exec tfplugindocs migrate` invocations. This generated a test failure matching the bug report:
```
--- FAIL: Test_SchemaJson_MigrateAcceptanceTests (0.00s)
--- FAIL: Test_SchemaJson_MigrateAcceptanceTests/time_provider_multiple_runs (0.32s)
testscript.go:558: # Copyright (c) HashiCorp, Inc.
> cmpenv templates/index.md.tmpl exp-templates/index.md.tmpl
diff templates/index.md.tmpl exp-templates/index.md.tmpl
--- templates/index.md.tmpl
+++ exp-templates/index.md.tmpl
@@ -31,36 +31,3 @@
`triggers` are *not* treated as sensitive attributes; a value used for `triggers` will be displayed in Terraform UI output as plaintext.
To force a these actions to reoccur without updating `triggers`, the …
```
> migrate: Ensure idempotency when ran multiple times

- .changes/unreleased/NOTES-20240531-093539.yaml
- README.md
- cmd/tfplugindocs/testdata/scripts/schema-json/validate/framework_provider_success_legacy_docs.txtar
- cmd/tfplugindocs/testdata/scripts/schema-json/validate/framework_provider_success_registry_docs.txtar
- internal/check/directory.go
- internal/check/directory_test.go
- internal/provider/validate.go
Reference: https://github.com/hashicorp/terraform-registry/pull/3811
This check is no longer valid due to a change in the Terraform Registry.
> validate: Remove number of files check

- .changes/unreleased/BUG FIXES-20240603-092911.yaml
- internal/schemamd/render.go
- internal/schemamd/render_test.go
- internal/schemamd/testdata/deep_nested_attributes.md
- internal/schemamd/testdata/deep_nested_attributes.schema.json
Closes #380
After introducing the new unit test matching the given schema and expected output, prior to the logic change:
```
--- FAIL: TestRender (0.00s)
--- FAIL: TestRender/deep_nested_attributes (0.00s)
/Users/bflad/src/github.com/hashicorp/terraform-plugin-docs/internal/schemamd/render_test.go:91: Unexpected diff (-wanted, +got):   strings.Join({
  	... // 1062 identical bytes
  	"el_two.level_three.level_four_primary. (see [below for nested sc",
  	"hema](#nestedatt--level_one--level_two--level_three--level_four_",
- 	"prim",
+ 	"second",
  	"ary--level_five))\n- `level_four_primary_string` (String) Parent ",
  	"should be level_one.level_two.level_three.level_four_primary.\n\n<",
  	`a id="nestedatt--level_one--level_two--level_three--level_four_`,
- 	"prim",
+ 	"second",
   …
```
> generate: Prevent incorrect attribute association with very deep nesting

- .changes/unreleased/NOTES-20240909-102809.yaml
- go.mod
- tools/go.mod
Ref: https://github.com/hashicorp/terraform-providers-devex-internal/issues/182
Bumps the minimum Go module to 1.22.7
> all: Bump minimum Go module version to 1.22

- go.mod
- go.sum
- internal/mdplain/renderer.go
- internal/provider/migrate.go
This reverts commit 8b2645d33ebb685b19030284154b5c7c1510fedf (PR #484)
In #484, the markdown rendering logic in `mdplain `package was refactored due to the deprecation of the `(*BaseNode).Text()` method in the `yuin/goldmark` library. The approach in that PR didn't cover all edge cases scenarios, as demonstrated by #497, so we are reverting that PR for now to unblock the upcoming `v0.22.0` release
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
No
> Revert "Bump github.com/yuin/goldmark from 1.7.7 to 1.7.12 (#484)"

- .github/workflows/test.yml
N/A
The `push` event does not run for public forks, so we should switch to using the `pull_request` target so that we get the "requires approval" dialogue: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories
No
> chore: Fix CI to run on public forks
